/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        SPIDER_KIT_CATEGORY: 'Spider Robot Kit',
        MS_INIT: '蜘蛛机器人初始化',
        MS_RESET: '蜘蛛机器人复位',
        MS_FORWARD: '蜘蛛机器人前进',
        MS_STEP: '步',
        MS_BACK: '蜘蛛机器人后退',
        MS_LEFT: '蜘蛛机器人向左移',
        MS_RIGHT: '蜘蛛机器人向右移',
        MS_PS2INIT: 'PS2初始化',
        MS_PS2PRESSED: 'PS2键被按下',
        MS_PS2PRESS: 'PS2按下',
        MS_PS2UP: '上',
        MS_PS2DOWN: '下',
        MS_PS2LEFT: '左',
        MS_PS2RIGHT: '右',
        MS_PS2LEFT1: '左1',
        MS_PS2LEFT2: '左2',
        MS_PS2LEFT3: '左3',
        MS_PS2RIGHT1: '右1',
        MS_PS2RIGHT2: '右2',
        MS_PS2RIGHT3: '右3',
        MS_PS2SELECT: '选择',
        MS_PS2START: '开始',
        MS_PS2RELEASE: 'PS2松开',
        MS_PS2GETROCKERVALUE: '获取摇杆值',
        MS_PS2LEFTX: '左横轴',
        MS_PS2LEFTY: '左纵轴',
        MS_PS2RIGHTX: '右横轴',
        MS_PS2RIGHTY: '右纵轴',
        MS_PS2STATUS: '读取PS2状态',
        MS_PS2LEFTANGLE: '左',
        MS_PS2RIGHTANGLE: '右',
        MS_PS2GETROCKERVALUE2: 'PS2获取',
        MS_PS2GETROCKERANGLE: '摇杆角度'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        SPIDER_KIT_CATEGORY: '蜘蛛机器人套件',
        MS_INIT: '蜘蛛机器人初始化',
        MS_RESET: '蜘蛛机器人复位',
        MS_FORWARD: '蜘蛛机器人前进',
        MS_STEP: '步',
        MS_BACK: '蜘蛛机器人后退',
        MS_LEFT: '蜘蛛机器人向左移',
        MS_RIGHT: '蜘蛛机器人向右移',
        MS_PS2INIT: 'PS2初始化',
        MS_PS2PRESSED: 'PS2键被按下',
        MS_PS2PRESS: 'PS2按下',
        MS_PS2UP: '上',
        MS_PS2DOWN: '下',
        MS_PS2LEFT: '左',
        MS_PS2RIGHT: '右',
        MS_PS2LEFT1: '左1',
        MS_PS2LEFT2: '左2',
        MS_PS2LEFT3: '左3',
        MS_PS2RIGHT1: '右1',
        MS_PS2RIGHT2: '右2',
        MS_PS2RIGHT3: '右3',
        MS_PS2SELECT: '选择',
        MS_PS2START: '开始',
        MS_PS2RELEASE: 'PS2松开',
        MS_PS2GETROCKERVALUE: '获取摇杆值',
        MS_PS2LEFTX: '左横轴',
        MS_PS2LEFTY: '左纵轴',
        MS_PS2RIGHTX: '右横轴',
        MS_PS2RIGHTY: '右纵轴',
        MS_PS2STATUS: '读取PS2状态',
        MS_PS2LEFTANGLE: '左',
        MS_PS2RIGHTANGLE: '右',
        MS_PS2GETROCKERVALUE2: 'PS2获取',
        MS_PS2GETROCKERANGLE: '摇杆角度'
    });
    return Blockly;
}

exports = addMsg;
