/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        WARDEN_CATEGORY: 'Warden Kit',
        WARDEN_RUN: 'warden %1 with speed %2',
        WARDEN_RUN_FORWARD: 'run forward',
        WARDEN_RUN_BACKWARD: 'run backward',
        WARDEN_TURN_LEFT: 'turn left',
        WARDEN_TURN_RIGHT: 'turn right',
        WARDEN_SETMOTOR: 'set %1 motor speed %2',
        WARDEN_SETLED: 'set %1 led %2',
        WARDEN_STATE_ON: 'on',
        WARDEN_STATE_OFF: 'off',
        WARDEN_SETBUZZER: 'set %1 buzzer %2',
        WARDEN_GETDUALLINETRACKER: 'dual line tracker %1 %2 detected %3',
        WARDEN_SIDE_LEFT: 'left side',
        WARDEN_SIDE_RIGHT: 'right side',
        WARDEN_COLOR_BLACK: 'black',
        WARDEN_COLOR_WHITE: 'white',
        WARDEN_GETFOURLINETRACKER: 'four line tracker %1 %2 %3 detected %4',
        WARDEN_GETTOUCH: 'touch switch %1 detected %2',
        WARDEN_STATE_ACTIVE: 'active',
        WARDEN_STATE_INACTIVE: 'inactive',
        WARDEN_GETULTRASONIC: 'ultrasonic %1 read distance (cm)',
        WARDEN_READPS2: 'read ps2 button',
        WARDEN_GETPS2PRESSED: 'ps2 %1 button was pressed',
        WARDEN_GETPS2RELEASED: 'ps2 %1 button was released',
        WARDEN_GETPS2KEEPPRESSED: 'ps2 %1 button keep pressing',
        WARDEN_GETPS2STICKANALOG: 'get ps2 %1 stick value',
        WARDEN_PS2_UP: 'up',
        WARDEN_PS2_DOWN: 'down',
        WARDEN_PS2_LEFT: 'left',
        WARDEN_PS2_RIGHT: 'right',
        WARDEN_PS2_TRIANGLE: 'triangle',
        WARDEN_PS2_CIRCLE: 'circle',
        WARDEN_PS2_CROSS: 'cross',
        WARDEN_PS2_SQUARE: 'square',
        WARDEN_PS2_SELECT: 'select',
        WARDEN_PS2_START: 'start',
        WARDEN_PS2_LX: 'left horizontal',
        WARDEN_PS2_LY: 'left vertical',
        WARDEN_PS2_RX: 'right horizontal',
        WARDEN_PS2_RY: 'right vertical'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        WARDEN_CATEGORY: 'Warden套件',
        WARDEN_RUN: 'warden %1 速度为 %2',
        WARDEN_RUN_FORWARD: '向前',
        WARDEN_RUN_BACKWARD: '向后',
        WARDEN_TURN_LEFT: '左转',
        WARDEN_TURN_RIGHT: '右转',
        WARDEN_SETMOTOR: '设置 %1 电机速度为 %2',
        WARDEN_SETLED: '设置 %1 led %2',
        WARDEN_STATE_ON: '开',
        WARDEN_STATE_OFF: '关',
        WARDEN_SETBUZZER: '设置 %1 蜂鸣器 %2',
        WARDEN_GETDUALLINETRACKER: '双路巡线 %1 %2 检测到 %3',
        WARDEN_SIDE_LEFT: '左侧',
        WARDEN_SIDE_RIGHT: '右侧',
        WARDEN_COLOR_BLACK: '黑色',
        WARDEN_COLOR_WHITE: '白色',
        WARDEN_GETFOURLINETRACKER: '四路巡线 %1 %2 %3 检测到 %4',
        WARDEN_GETTOUCH: '触摸开关 %1 检测到 %2',
        WARDEN_STATE_ACTIVE: '激活',
        WARDEN_STATE_INACTIVE: '未激活',
        WARDEN_GETULTRASONIC: '超声波 %1 读取距离 (cm)',
        WARDEN_READPS2: '读取 ps2 按键',
        WARDEN_GETPS2PRESSED: 'ps2 %1 按键被按下',
        WARDEN_GETPS2RELEASED: 'ps2 %1 按键被放开',
        WARDEN_GETPS2KEEPPRESSED: 'ps2 %1 按键持续按下',
        WARDEN_GETPS2STICKANALOG: '读取 ps2 %1 摇杆数值',
        WARDEN_PS2_UP: '上',
        WARDEN_PS2_DOWN: '下',
        WARDEN_PS2_LEFT: '左',
        WARDEN_PS2_RIGHT: '右',
        WARDEN_PS2_TRIANGLE: '三角',
        WARDEN_PS2_CIRCLE: '圆圈',
        WARDEN_PS2_CROSS: '叉号',
        WARDEN_PS2_SQUARE: '方块',
        WARDEN_PS2_SELECT: '选择',
        WARDEN_PS2_START: '开始',
        WARDEN_PS2_LX: '左水平',
        WARDEN_PS2_LY: '左垂直',
        WARDEN_PS2_RX: '右水平',
        WARDEN_PS2_RY: '右垂直'
    });
    return Blockly;
}

exports = addMsg;
